name: LangPie Action

on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  langpie-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Install dependencies
        run: |
          yarn install

      - name: Build docs
        run: |
          yarn docs:build

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: ${{ secrets.CNAME }}
          commit_message: ${{ github.event.head_commit.message }}
          publish_branch: 'gh-pages'
          publish_dir: 'docs/.vuepress/dist'
          force_orphan: true
          enable_jekyll: true
          keep_files: true
